// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// mspline
arma::mat mspline(arma::colvec x, double tmin, double tmax, arma::colvec tint, int k);
RcppExport SEXP _spleen_mspline(SEXP xSEXP, SEXP tminSEXP, SEXP tmaxSEXP, SEXP tintSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type tint(tintSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(mspline(x, tmin, tmax, tint, k));
    return rcpp_result_gen;
END_RCPP
}
// ispline
arma::mat ispline(arma::colvec x, double tmin, double tmax, arma::colvec tint, int k);
RcppExport SEXP _spleen_ispline(SEXP xSEXP, SEXP tminSEXP, SEXP tmaxSEXP, SEXP tintSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type tint(tintSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(ispline(x, tmin, tmax, tint, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spleen_mspline", (DL_FUNC) &_spleen_mspline, 5},
    {"_spleen_ispline", (DL_FUNC) &_spleen_ispline, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_spleen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
