# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mspline <- function(x, tmin, tmax, tint, k) {
    .Call(`_spleen_mspline`, x, tmin, tmax, tint, k)
}

ispline <- function(x, tmin, tmax, tint, k) {
    .Call(`_spleen_ispline`, x, tmin, tmax, tint, k)
}

